language: java
sudo: false
branches:
  only:
    - master

after_success:
  - mvn deploy --settings src/main/config/travis-settings.xml

env:
  global:
    - secure: "Lpead8dDNukk0E0UvkrmCTyG8vizDU319aFvUwl2W13VnvjswY7ovvCc4tBeRSUBTthZTjM4W2o6gTA/QnLLVws3PSKdKOGnvSPB/r0qUmbNUqv7z6cOXzE7JbDRZC4cb12kaL+ooyENkVXieBIzvO+VhP80+p4HSlIkarTpi3U="
    - secure: "rK5Ug2yKbyERVBEp5UGaSHPD+Ssk5V6ptNfcCEy6FvBPwgA4Q8gqJCxW5VKaFJEpMt7jut311nSfQx6S0DG8sfL0eApkHc2GqD6lPZM0L7CdYSoWoaFXmCiKzSpRAOxI10w46sP8SppQSNnCEDEn5Gw9XqOZVnnO98cDMPSbYso="